---

- hosts: all
  become: true
  vars_files:
    - 'config.yml'
    - 'private_config.yml'
  roles:
  - syncthing
  - discosrv
  - relaysrv


# - { role: debian_stock_config, when: ansible_os_family == 'Debian' }
